#!/usr/bin/env sh
# Compile SwapVMProgramBuilder and publish its artifact for the Python adapter.
#
# The artifact is committed (unlike out/, which is gitignored) so that the
# Python side works on a fresh clone with NO Foundry toolchain — Lane B and the
# macOS teammate consume venues/aqua/ without ever installing forge. Re-run this
# whenever SwapVMProgramBuilder.sol changes.
#
# POSIX sh: runs unchanged in WSL, on macOS and in CI.
set -eu

cd "$(dirname "$0")"

if [ ! -d node_modules/@1inch/swap-vm ]; then
  echo "installing solidity dependencies..."
  # --ignore-workspace is REQUIRED: without it pnpm walks up, finds the repo
  # root workspace, and installs the web app's dependencies here instead.
  pnpm install --ignore-workspace --no-frozen-lockfile
fi

echo "compiling..."
forge build

echo "extracting artifact -> ../program_builder.json"
forge inspect SwapVMProgramBuilder deployedBytecode --json > /tmp/swapvm-runtime.json
node -e '
  const fs = require("fs");
  const runtime = JSON.parse(fs.readFileSync("/tmp/swapvm-runtime.json", "utf8"));
  const artifact = JSON.parse(fs.readFileSync("out/SwapVMProgramBuilder.sol/SwapVMProgramBuilder.json", "utf8"));
  fs.writeFileSync("../program_builder.json", JSON.stringify({
    _comment: "Generated by venues/aqua/solidity/build.sh — do not edit by hand.",
    contract: "SwapVMProgramBuilder",
    solcVersion: "0.8.30",
    deployedBytecode: typeof runtime === "string" ? runtime : runtime.object,
    abi: artifact.abi,
  }, null, 2) + "\n");
'
rm -f /tmp/swapvm-runtime.json
echo "done."
