#!/usr/bin/env sh
# Compile SwapVMProgramBuilder and publish its artifact for the Python adapter.
#
# The artifact is committed (unlike out/, which is gitignored) so that the
# Python side works on a fresh clone with NO Foundry toolchain — Lane B and the
# macOS teammate consume venues/aqua/ without ever installing forge. Re-run this
# whenever SwapVMProgramBuilder.sol changes.
#
# POSIX sh: runs unchanged in WSL, on macOS and in CI.
set -eu

cd "$(dirname "$0")"

if [ ! -d node_modules/@1inch/swap-vm ]; then
  echo "installing solidity dependencies..."
  # --ignore-workspace is REQUIRED: without it pnpm walks up, finds the repo
  # root workspace, and installs the web app's dependencies here instead.
  pnpm install --ignore-workspace --no-frozen-lockfile
fi

echo "compiling..."
forge build

echo "extracting artifact -> ../program_builder.json"
forge inspect SwapVMProgramBuilder deployedBytecode --json > /tmp/swapvm-runtime.json
node -e '
  const fs = require("fs");
  // `forge inspect ... --json` has emitted three different shapes across Foundry
  // versions: a JSON string ("0x.."), an object ({object: "0x.."}), and — since
  // Foundry 1.x — a BARE unquoted 0x hex blob, which is not valid JSON at all and
  // made JSON.parse throw. Parse defensively and fall back to the raw text.
  const raw = fs.readFileSync("/tmp/swapvm-runtime.json", "utf8").trim();
  let runtime;
  try { runtime = JSON.parse(raw); } catch { runtime = raw; }
  const artifact = JSON.parse(fs.readFileSync("out/SwapVMProgramBuilder.sol/SwapVMProgramBuilder.json", "utf8"));
  const bytecode = typeof runtime === "string" ? runtime : runtime.object;
  // Read the swap-vm pin out of package.json rather than hardcoding it. Request #29 was
  // caused by programs compiled against a swap-vm that did not match what is deployed on
  // Base, and this field is the record of which one produced this artifact. An earlier
  // version of this script omitted it entirely, so regenerating silently DELETED the
  // provenance from the committed file. Deriving it means it cannot drift from the pin.
  const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
  const pinned = (pkg.dependencies["@1inch/swap-vm"] || "").split("#")[1] || "UNPINNED";
  // Refuse to publish a bad artifact rather than overwrite a good committed one. This
  // file is consumed by the Python adapter on fresh clones that have no Foundry, so a
  // silently truncated or empty value would surface far from here as a failing eth_call.
  if (!/^0x[0-9a-fA-F]{64,}$/.test(bytecode || "")) {
    console.error("refusing to write ../program_builder.json: extracted deployedBytecode " +
                  "is not plausible hex (got " + JSON.stringify(String(bytecode).slice(0, 40)) + ")");
    process.exit(1);
  }
  fs.writeFileSync("../program_builder.json", JSON.stringify({
    _comment: "Generated by venues/aqua/solidity/build.sh - do not edit by hand.",
    contract: "SwapVMProgramBuilder",
    solcVersion: "0.8.30",
    swapVmVersion: pinned + " (pinned to match the contract deployed on Base)",
    deployedBytecode: bytecode,
    abi: artifact.abi,
  }, null, 2) + "\n");
'
rm -f /tmp/swapvm-runtime.json
echo "done."
