"""Pydantic mirror of the frozen JSON Schemas in packages/schema/*.json.

The JSON Schema files are the source of truth; this is the Python view of them.
If the two ever disagree, the JSON is right. `test_conformance.py` validates the
shared golden fixtures against BOTH, which is what keeps them from drifting.

FROZEN after Wave 0. Need a change? File a request in docs/active-work.md —
do not edit this file from inside a lane.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

# uint256 exceeds float64, so amounts cross the boundary as decimal strings.
Uint256Str = Annotated[str, Field(pattern=r"^[0-9]+$")]
Address = Annotated[str, Field(pattern=r"^0x[a-fA-F0-9]{40}$")]
Bytes32 = Annotated[str, Field(pattern=r"^0x[a-fA-F0-9]{64}$")]
HexData = Annotated[str, Field(pattern=r"^0x([a-fA-F0-9]{2})*$")]


class Frozen(BaseModel):
    """Reject unknown fields everywhere. A typo in a lane should fail loudly at
    the boundary, not silently propagate a field nobody reads."""

    model_config = ConfigDict(extra="forbid")


# ── Mandate ───────────────────────────────────────────────────────────────


class MandateConstraints(Frozen):
    allowed_assets: list[str] = Field(min_length=1)
    max_slippage_bps: int = Field(ge=0, le=10_000)
    max_position_pct: float = Field(default=1.0, ge=0, le=1)
    min_cash_pct: float = Field(default=0.0, ge=0, le=1)
    rebalance_cooldown_seconds: int = Field(default=3600, ge=0)
    max_actions_per_tick: int = Field(default=3, ge=1)
    #: Soft band on the ALLOCATION AND EXPOSURE constraints only. A breach no
    #: larger than the band is accepted with a warning on the `AgentAction`
    #: instead of rejected — 61% against a 60% cap is a swap that priced a hair
    #: differently, not a change of intent.
    #:
    #: RELATIVE to the constraint's own value, never absolute percentage points:
    #: a ceiling C admits C*(1+band), a floor F admits F*(1-band), a target T
    #: admits |actual-T| <= T*band.
    #:
    #: Applies to `max_position_pct`, `min_cash_pct`, target-allocation drift.
    #: Never to `max_slippage_bps` — that ceiling was already compared against a
    #: worst-case bound rather than an estimate, so banding it means silently
    #: paying more than the mandate's stated maximum cost. Never to
    #: `allowed_assets` / `permitted_venues` / `permitted_data_sources`: there is
    #: no "5% of an asset that isn't permitted". Never to `max_actions_per_tick`
    #: or `rebalance_cooldown_seconds`, where a band is just a bigger limit.
    #:
    #: Measure drift against the MANDATE, not against last tick, or in-band
    #: acceptances ratchet the book away from it without ever being rejected.
    #: 0 restores strict rejection.
    tolerance_band_pct: float = Field(default=0.05, ge=0, le=0.5)


class Persona(Frozen):
    """How the agent argues, and what it prefers among options already permitted.

    INVARIANT, pinned by a test in `agent/`: a persona **skews preference inside
    the permitted set and can never widen it.** An aggressive persona may prefer
    the riskier of two permitted assets; it may not reach an asset
    `allowed_assets` omits, raise a cap, shrink the cash floor, or loosen the
    slippage ceiling. Persona is taste; constraints are law. If the two ever
    merge, "aggressive" stops being a style and becomes an exploit.
    """

    #: Display name, shown beside the decision feed.
    name: str = Field(min_length=1, max_length=80)
    #: How it writes its reasoning. Composed into the system prompt, so it shapes
    #: the text a depositor reads — not the bounds the harness enforces.
    voice: str = Field(min_length=1, max_length=500)
    #: Stated leanings, each a preference between options the mandate allows.
    biases: list[Annotated[str, Field(min_length=1, max_length=200)]] = Field(
        default_factory=list, max_length=10
    )
    #: How readily it acts on a thesis. Steers sizing WITHIN `max_position_pct`
    #: and how often it holds; it changes no bound.
    conviction: Literal["low", "medium", "high"] = "medium"


class Mandate(Frozen):
    """Soft, LLM-side, mutable only by the agent after genesis."""

    version: int = Field(ge=1)
    name: str = Field(min_length=1, max_length=80)
    objective: str = Field(min_length=1, max_length=2000)
    base_asset: str
    constraints: MandateConstraints
    #: Registry keys resolved by the data layer. Granting a new source is a
    #: mandate edit, not a code change — this is the extension point.
    permitted_data_sources: list[str] = Field(min_length=1)
    #: "aave" joined in Wave 1. Kept a closed Literal rather than a free
    #: string: a mandate naming a venue with no adapter produces a vault
    #: whose agent proposes trades the harness can only ever reject.
    permitted_venues: list[Literal["uniswap", "aqua", "aave"]] = Field(min_length=1)
    created_at: datetime | None = None
    risk_posture: Literal["conservative", "balanced", "aggressive"] = "balanced"
    #: Optional character the agent argues in. None means a neutral curator.
    persona: Persona | None = None
    update_rules: str | None = Field(default=None, max_length=1000)


# ── MarketSnapshot ────────────────────────────────────────────────────────

FactKind = Literal[
    "yield",
    "price",
    "tvl",
    "liquidity",
    "volatility",
    "utilization",
    "volume",
    #: Normalised 0-1 market-mood index; 0 is extreme fear, 1 extreme greed.
    "sentiment",
    #: What it costs to transact. A 3 bps edge is not an edge if the
    #: rebalance that captures it costs more than it earns.
    "gas",
]
FactUnit = Literal["apy_fraction", "usd", "ratio", "bps", "token_amount"]


class FactSubject(Frozen):
    protocol: str | None = None
    market: str | None = None
    token: str | None = None
    pair: list[str] | None = Field(default=None, min_length=2, max_length=2)
    chain: str = "base"


class Fact(Frozen):
    """One observation, carrying its own provenance.

    Deliberately generic: a source describes whatever it knows and leaves the
    rest unset. That is what lets Chainlink or Pyth drop in later without any
    schema change.
    """

    id: str
    kind: FactKind
    subject: FactSubject
    value: float
    #: apy_fraction is 0.0432 for 4.32%. Normalize at the source adapter.
    unit: FactUnit
    #: Registry key of the contributing source — the provenance the UI shows.
    source: str
    observed_at: datetime
    confidence: float | None = Field(default=None, ge=0, le=1)


class SourceError(Frozen):
    source: str
    message: str


class SourceNote(Frozen):
    """Context about a source that is *not* a failure.

    Split out from `SourceError` because the two are read differently and the
    conflation was doing real damage: 35 of the 36 journalled ticks reported
    "USDC is a quote token on this venue" as an error, and the prompt renders
    errors as *data you could not read* and asks the model to reason about the
    gap. A category mistake and a deliberate skip are not gaps.
    """

    source: str
    message: str


class MarketSnapshot(Frozen):
    """Source-agnostic by construction: a flat list of facts, not a provider's
    response shape. The registry merges partial contributions from every
    permitted source into one of these."""

    taken_at: datetime
    facts: list[Fact] = Field(default_factory=list)
    #: A failing source degrades the snapshot; it never crashes the loop. The
    #: model is shown these so it knows what it could not see.
    errors: list[SourceError] = Field(default_factory=list)
    #: Non-failures worth stating. Shown to the model as context, never as a gap.
    notes: list[SourceNote] = Field(default_factory=list)


# ── AllocationDecision ────────────────────────────────────────────────────


class TargetAllocation(Frozen):
    asset: str
    weight: float = Field(ge=0, le=1)


class SwapIntent(Frozen):
    """Rotate what the vault holds. Uniswap is the taker-side venue."""

    venue: Literal["uniswap"] = "uniswap"
    kind: Literal["swap"] = "swap"
    token_in: str
    token_out: str
    amount_in: Uint256Str | None = None
    #: Easier for a model to get right than base units.
    pct_of_holdings: float | None = Field(default=None, ge=0, le=1)


class AquaProgram(Frozen):
    shape: Literal["xyc", "pegged"] = "xyc"
    fee_bps: int | None = Field(default=None, ge=0, le=10_000)


class AquaShipIntent(Frozen):
    """Open/resize a market-making position. Tokens never leave the vault."""

    venue: Literal["aqua"] = "aqua"
    kind: Literal["ship"] = "ship"
    tokens: list[str] = Field(min_length=1)
    amounts: list[Uint256Str] = Field(min_length=1)
    #: Parameters only — Lane D compiles bytecode via the Solidity ProgramBuilder.
    program: AquaProgram | None = None


class AquaDockIntent(Frozen):
    venue: Literal["aqua"] = "aqua"
    kind: Literal["dock"] = "dock"
    strategy_hash: Bytes32


class SupplyIntent(Frozen):
    """Deposit an asset into a lending market to earn interest.

    The gap this closes: the `aave` data source contributed 204 facts about
    lending yields across the first 36 ticks, and there was no intent type that
    could act on any of them. The agent read yields it structurally could not
    capture, and its only possible response to "Aave pays 3.5% on USDC" was a
    Uniswap swap between USDC and WETH.

    Custody is preserved. The vault supplies and receives the aToken, which it
    holds itself — nothing is delegated and `onBehalfOf` is always the vault.
    """

    venue: Literal["aave"] = "aave"
    kind: Literal["supply"] = "supply"
    asset: str
    amount: Uint256Str | None = None
    #: Easier for a model to get right than base units, same as SwapIntent.
    pct_of_holdings: float | None = Field(default=None, ge=0, le=1)


class WithdrawIntent(Frozen):
    """Redeem a supplied asset from a lending market back into the vault."""

    venue: Literal["aave"] = "aave"
    kind: Literal["withdraw"] = "withdraw"
    asset: str
    #: Omit for "all of it" — `type(uint256).max` at the adapter, which is how
    #: Aave expresses a full withdrawal without racing accrued interest.
    amount: Uint256Str | None = None


VenueIntent = SwapIntent | AquaShipIntent | AquaDockIntent | SupplyIntent | WithdrawIntent


class MandateAmendment(Frozen):
    rationale: str = Field(max_length=1000)
    #: Partial Mandate, merged over the current one then re-validated.
    patch: dict[str, Any]


class AllocationDecision(Frozen):
    """What the LLM must emit, exactly.

    Load-bearing: the agent holds a key and executes directly, and small open
    models produce malformed structured output. The harness validates against
    this and reject-and-retries. Nothing reaches the chain unvalidated.
    """

    #: 'hold' is a first-class answer. A model that never holds churns the vault.
    action: Literal["hold", "rebalance", "enter", "exit"]
    #: Surfaced verbatim in the dApp decision feed — this is the product.
    reasoning: str = Field(min_length=1, max_length=2000)
    #: Fact ids that drove this. Lets the UI show data → reasoning → tx, and
    #: lets us catch a model inventing numbers.
    facts_used: list[str] = Field(default_factory=list)
    target_allocations: list[TargetAllocation] | None = None
    venue_intents: list[VenueIntent] | None = None
    confidence: float | None = Field(default=None, ge=0, le=1)
    mandate_amendment: MandateAmendment | None = None


# ── ExecutionPlan ─────────────────────────────────────────────────────────


class ExecutionStep(Frozen):
    #: Must be on the vault's allowlist or execute() reverts.
    target: Address
    value: Uint256Str = "0"
    calldata: HexData
    #: Per-step explanation — makes the feed readable and failures diagnosable.
    why: str = Field(max_length=200)


class ExecutionPlan(Frozen):
    """Concrete transactions from a venue adapter, executed by the vault.

    This is the seam keeping Lanes A and D apart: Lane D builds arbitrary
    calldata off-chain and never touches contracts/; the vault exposes one
    generic allowlisted execute() and never learns what a venue is.
    """

    venue: str
    steps: list[ExecutionStep] = Field(min_length=1)
    expected_effect: str | None = Field(default=None, max_length=500)
    #: Harness rejects the plan if this exceeds mandate max_slippage_bps.
    expected_slippage_bps: int | None = Field(default=None, ge=0)
    #: Router quotes go stale; do not submit past this.
    quote_expires_at: datetime | None = None


# ── AgentAction ───────────────────────────────────────────────────────────


class ModelProvenance(Frozen):
    backend: str | None = None
    name: str | None = None
    #: Malformed outputs rejected before a valid one — the honest cost of
    #: small open models, worth surfacing rather than hiding.
    validation_retries: int = Field(default=0, ge=0)


class ConstraintWarning(Frozen):
    """One banded acceptance — a constraint that bent and was allowed to.

    Structured rather than a formatted sentence so the dApp can state which
    constraint bent and by how much, and so the reflection can price the drift
    without re-parsing prose.
    """

    #: Closed on purpose. A second warning class is a schema change, so nobody
    #: can quietly start recording a different kind of exception in this array.
    kind: Literal["tolerance_band"] = "tolerance_band"
    #: The `MandateConstraints` field that bent, or "target_allocation" for
    #: drift. Never `max_slippage_bps` or an allowlist — outside the band by
    #: design.
    constraint: str
    #: Asset symbol when the constraint is per-asset; None for portfolio-wide.
    subject: str | None = None
    #: The mandate's own value — what the band is measured against, and what the
    #: agent is still steering back toward.
    limit: float
    #: The projected post-execution value that breached the limit.
    actual: float
    #: The band in force when this was accepted. Recorded on the action rather
    #: than looked up later, because the agent may amend its own mandate and a
    #: warning must stay readable against the rules that actually applied.
    band_pct: float = Field(ge=0, le=0.5)
    #: One sentence for the feed.
    message: str = Field(min_length=1, max_length=300)


class AgentAction(Frozen):
    """One complete decision cycle. The audit trail and the demo feed.

    Recorded even when the agent holds or fails — a curator that did nothing
    and said why is still curating.
    """

    id: str
    vault: Address
    timestamp: datetime
    #: 'rejected' = failed schema/constraint validation, never reached the
    #: chain. Keep these; they evidence that validation is load-bearing.
    status: Literal["pending", "executed", "held", "rejected", "failed"]
    snapshot: MarketSnapshot | None = None
    decision: AllocationDecision | None = None
    plan: ExecutionPlan | None = None
    tx_hashes: list[Bytes32] = Field(default_factory=list)
    mandate_version_before: int | None = Field(default=None, ge=1)
    mandate_version_after: int | None = Field(default=None, ge=1)
    model: ModelProvenance | None = None
    error: str | None = None
    #: Constraints this cycle breached and was accepted anyway, within
    #: `tolerance_band_pct`. Distinct from `error`, which is why a cycle stopped:
    #: a warning rides on a *successful* action. Render these wherever the action
    #: is rendered — an invisible band is indistinguishable from no rule at all.
    warnings: list[ConstraintWarning] = Field(default_factory=list)
    duration_ms: int | None = Field(default=None, ge=0)


# ── VaultState ────────────────────────────────────────────────────────────


class Holding(Frozen):
    token: Address
    symbol: str
    balance: Uint256Str
    decimals: int | None = Field(default=None, ge=0, le=36)
    #: Valued with the same Chainlink feed totalAssets() uses, so the UI and
    #: the contract never disagree.
    value_in_asset: Uint256Str | None = None
    #: Venue key if this balance backs an open position. Flags encumbrance,
    #: not location — the vault still custodies it.
    committed_to_venue: str | None = None
    #: The symbol this holding is economically equivalent to, when it is not
    #: itself. `aBasUSDC` represents `USDC`.
    #:
    #: Exists so nothing downstream has to know what an aToken is. A receipt
    #: token is not a new exposure — supplying USDC to Aave does not make the
    #: vault less long USDC — so allocation weights, mandate targets and the
    #: allocation chart must all fold it back. Without this, a mandate allowing
    #: ["USDC","WETH"] sees a vault holding 50% of an asset it never permitted,
    #: and every constraint layer fights a position that is exactly what the
    #: mandate asked for.
    represents: str | None = None


class AquaStrategy(Frozen):
    strategy_hash: Bytes32
    tokens: list[Address] = Field(default_factory=list)
    app: Address | None = None
    shipped_at: datetime | None = None


class VaultState(Frozen):
    """Invariant: the vault is sole custodian (Pattern 1). Capital never leaves
    it — Aqua tracks virtual balances while tokens stay put — so `holdings` is
    literally the vault's balances and `total_assets` derives from them."""

    address: Address
    asset: Address
    total_assets: Uint256Str
    total_supply: Uint256Str
    holdings: list[Holding] = Field(default_factory=list)
    asset_decimals: int = Field(default=6, ge=0, le=36)
    share_price: str | None = None
    #: Holder of AGENT_ROLE. Executes directly with no human override — that
    #: is the trust model, stated plainly.
    agent: Address | None = None
    #: keccak256 of the canonical mandate JSON, recorded at genesis. Lets a
    #: depositor verify the mandate they were shown is the one deployed.
    mandate_hash: Bytes32 | None = None
    aqua_strategies: list[AquaStrategy] = Field(default_factory=list)
    paused: bool = False
    block_number: int | None = Field(default=None, ge=0)


# ── VaultPerformance ──────────────────────────────────────────────────────


class AllocationSlice(Frozen):
    """One asset's share of the vault at one moment."""

    symbol: str
    value_in_asset: Uint256Str
    committed_to_venue: str | None = None


class PerformancePoint(Frozen):
    """One observation of a vault's worth. Never an interpolation.

    On a pinned fork blocks advance only when a transaction is mined, so this
    series is event-spaced rather than time-spaced. A flat stretch between two
    trades is the truth, and filling it in would be inventing history.
    """

    timestamp: datetime
    total_assets: Uint256Str
    total_supply: Uint256Str
    block_number: int | None = Field(default=None, ge=0)
    #: `convertToAssets(1e18)` in BASE-ASSET decimals — for a 6-decimal asset a
    #: price of 1.0025 is "1002506", not 1e18 (request #27). None while supply
    #: is zero, because a share of nothing has no price.
    share_price: str | None = None
    allocation: list[AllocationSlice] = Field(default_factory=list)
    source: Literal["tick", "sampler", "backfill"] = "tick"


class PerformanceSummary(Frozen):
    """Risk figures derived from the series. Never stored.

    Recomputed on every request, so a metric cannot drift from the series it
    describes. **Every figure is None rather than zero when the series cannot
    support it** — an annualized volatility from three points is not a small
    number, it is a meaningless one, and rendering 0.0% would be a claim.
    """

    observations: int = Field(ge=0)
    first_at: datetime | None = None
    last_at: datetime | None = None
    share_price: str | None = None
    total_assets: Uint256Str | None = None
    #: 0.0123 is +1.23% — the same fraction convention as `apy_fraction`.
    return_pct: float | None = None
    return_24h_pct: float | None = None
    return_7d_pct: float | None = None
    annualized_return_pct: float | None = None
    volatility_pct: float | None = None
    #: Largest peak-to-trough fall, positive. The number a depositor feels.
    max_drawdown_pct: float | None = None
    #: Annualized return over annualized volatility. Deliberately not called a
    #: Sharpe ratio: no risk-free rate is subtracted, so it is not one.
    risk_adjusted_return: float | None = None


class VaultPerformance(Frozen):
    vault: Address
    points: list[PerformancePoint] = Field(default_factory=list)
    summary: PerformanceSummary


__all__ = [
    "Mandate",
    "MandateConstraints",
    "Persona",
    "ConstraintWarning",
    "MarketSnapshot",
    "Fact",
    "FactSubject",
    "SourceError",
    "SourceNote",
    "AllocationDecision",
    "TargetAllocation",
    "SwapIntent",
    "AquaShipIntent",
    "AquaDockIntent",
    "SupplyIntent",
    "WithdrawIntent",
    "AquaProgram",
    "VenueIntent",
    "MandateAmendment",
    "ExecutionPlan",
    "ExecutionStep",
    "AgentAction",
    "ModelProvenance",
    "VaultState",
    "Holding",
    "AquaStrategy",
    "AllocationSlice",
    "PerformancePoint",
    "PerformanceSummary",
    "VaultPerformance",
]
